# Generated by Django 5.2.4 on 2025-09-24 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва задачі')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('priority', models.CharField(choices=[('Low', 'Низький пріорітет'), ('Medium', 'Середній пріорітет'), ('High', 'Високий пріорітет')], default='Low', max_length=30, verbose_name='Пріорітет')),
                ('status', models.CharField(choices=[('Pending', 'Потрібно виконати'), ('In-progress', 'В процесі'), ('Done', 'Виконано')], default='Pending', max_length=30, verbose_name='Cтатус')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Термін виконання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('file', models.FileField(blank=True, null=True, upload_to='task_files/', verbose_name='Файл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='comment_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.task')),
            ],
        ),
    ]
